# vim: set ts=2 sw=2 ft=yaml et:

version: "3.8"

services:
  # PostgreSQL
  postgres:
    container_name: bitban-postgres
    image: postgres:13
    environment:
      POSTGRES_DB: bitban
      POSTGRES_USER: bitban
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data/pgdata

  # Cache
  cache:
    container_name: bitban-cache
    image: redis:5

networks:
  default:
    name: bitban

volumes:
  # PostgreSQL Data
  postgres:
    name: bitban-postgres
