// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	CasbinRules  string
	UserEmails   string
	UserProfiles string
	UserTokens   string
	Users        string
}{
	CasbinRules:  "casbin_rules",
	UserEmails:   "user_emails",
	UserProfiles: "user_profiles",
	UserTokens:   "user_tokens",
	Users:        "users",
}
