# v0.0.*
app:
  host: ${APP_HOST}
  port: ${APP_PORT}

database:
  host: ${PSQL_HOST}
  port: ${PSQL_PORT}
  dbname: ${PSQL_DBNAME}
  user: ${PSQL_USER}
  pass: ${PSQL_PASS}

amqp:
  uri: ${AMPQ_URI}

redis:
  url: ${REDIS_URL}

security:
  accessTokenExpiresAt: 60
  refreshTokenExpiresAt: 259200

jwt:
  passphrase: ${JWT_PASSPHRASE}
  publicKey: |-
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFE
    Q0JpUUtCZ1FETzlNQkNTYXVRWU5EY0hZc01GWXM5VlIzZQpSWThZbXFHRERNcjdteTRaeEUxV2x0
    c2lZUFJGNjBCM1NTMElsSUIvcWgvcnVoZ1FFRUN4OG53dVpvcnNxd0JoCkk2bU10UGpvQ2o5U2dx
    K2hRckoveDNnemFGOW5XN3hjTDVkbUhwdVdhOTZhaHY3RUdRbWtPcmZCL0JkYVo3MFcKZmZoTk9E
    QlRUNDZMM1haWU1RSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
  privateKey: |-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRF
    Sy1JbmZvOiBBRVMtMTI4LUNCQyxFMjJCRUI4QUEwMjQ2MEY2ODAxN0MzOTQ5OUU4NTM4RAoKaUpH
    ZHFybUxMUHZUMTBLUG5aN1B3bHlrSGdBUExibFdPeFM5aFBrQ3VnVC83ejJNempwOTlzcDREOTRt
    NGFyNwpKMkljTlNLUm9hTEtsZDZ5am1acTFhNTBoWHZZV3YzamlVaVp3bnBKK1dYOE1Hbk94ODRS
    ZTJTM05GMXYxSlZrCjlFbE8venRmNmtDcG91N2xPTUJvS1hsUWhGa2ZMS29TRGZvVEdadytQdVZP
    UVcycmhweUNqeUpJUGVpZ0JaTE0KYnFINUYzdzFMd1RnUXA5cG1RdnNsWXFTNU1kS1lvWFc1dC92
    dTdxNGg1YzljTXFxZHpKRGlCajk0TWp1SEcvcgp0V2dRdC8yTnZSTDlySWQxcGNxWGRDeXVmV0ZW
    VDlCYzEzWlkwd3ZwT1FXdWVUTGdYYUx6Vi96LzVKNDlxVUNuCkFsSFozZHRHVnM4MkhkTzB2Unlo
    UnozNFdTczhaNDNpdktTalpueWJzeXJxeUVnYWpMcDVIQ3pzWnE3M09qN1cKaHg5QkZGZjBkTSt1
    SWhVNGtPeEhJREtaM3FEdllrcXN4ZHJ5SnMzTDFyNW5wSzF4N3g2bU9XaktXOVVvb041cAp2M3FT
    MlFzQWc5VkNKOTErRmlFREdNait5NzBhVmJrcGNOZ1RxN2lGZVA2aVk4cEt4aHp5bC9YYXFabUha
    OFZGCnpzck5QUW1iclkzQUM1QlhYbkVQN2VqTU1PTkZQa2h5TjNTSzJTY05YZWE0UVdoME9zN28z
    NGV2UTFOOUNDU3UKcWxTaENWcmVLSUhhM1JCS1hhUHQ1RFBvSUVkSS9VWlpMaVdQMWdSWWFneks0
    V3NQZmQvaVNvTkJVK1V5WG83QgpqNGhSSUkzTmYwUkZCc2pKZUVsRGdvbzc3VWwyRkd2L1pvaVU5
    SUw4VldpbUgwMnkzbVlqck9ZZG0wQzFMaFdHClN2ZDlOQ1h6azA4YUI4d0REN04wQzI0YVNxSitB
    eU5OOTJscUl3WHplRFJWamx4TkRqU3pEYlZ1UmNXWjRaUm4KWXhDQ3JLTUJ0eUw4Uy9tRlV6SVNs
    djh0Q3dEcURmWjdqOEVTVTA0Q3VlYmhnMCtSYjFqWXZ6MWUyV0NJNmFIWAotLS0tLUVORCBSU0Eg
    UFJJVkFURSBLRVktLS0tLQo=
