# v0.0.*
app:
  host: ${APP_HOST}
  port: ${APP_PORT}

git:
  backend: go
  storage: mem
  configs:
    init:
      defaultBranch: main

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  dbname: ${DATABASE_DB}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

redis:
  url: ${REDIS_URL}

security:
  accessTokenExpiresAt: 60
  refreshTokenExpiresAt: 259200

ssh:
  key:
    passphrase: password
    publicKey: |-
      LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFE
      Q0JpUUtCZ1FETE8zazJEa25IR0JRZjg0NWhLQUpjbUh6UgpNVTM2VE5lOE55R1orQSs3eW9wTDRS
      ZmM5UlVOUWExL1JiaFlNcTgyQXBRY0NxTEJFZnZGWmh6LzZiZmx4RUhsCkZsTFhBV1ZBUEtpbTBh
      b2pGVEFxbk8rVXVYV09nTkJYY2V5RlRFZkM1QitveGFZU1Z2a3A0VUZQRzBBOTR5NHMKZ1RHT3hW
      ZTJTeS9TaU40eFJRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
    privateKey: |-
      LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRF
      Sy1JbmZvOiBBRVMtMTI4LUNCQyxCQjU1OUJGMDhCNUE4NkQyMEI3NDlDMjg3OTBFNDRDQQoKSnJy
      OXk4ckFMY3Fsdkc5U01nUndPREw2N1ozc0w3ZndqZWJ1SGJpZVJ4S2lhZy9mQit1VlhpNVd1M2ZY
      WUM4ZQpTb2lLd0IrbWZGTEVFSDdVeUljcFlRTE1Gbk9kUHo1THFIcHNzbnpWVGpUTVdHS0Ywbk1R
      M0s1Nkl5enBaZE9GCm1mb3AzZXh0YlJzZnVhazYwVXFQWFFvZzN2bmdjVE9VK2xwVjdhYlF5Um16
      Z0NuajlpVXBCaFZaL2tQbU9LYUMKOXR4bnUzZnI1eW01R1RqaXhhTXhtMEI4UTFicExlcUR2QWNw
      T3VPTTM5a0JGcDBVdnJBcHpvWjZtUGhQaHIyRgpyVy8rWXZOKzJWZ3NObkQxNkhTSnc0TERCcnlF
      SG43OEp1MHI5bG0vR1pNY2hJdzBuMU9oVDUrOXhrZ3c5U2U4Ck1oeGhPb1lRZllkT3hXZFBFTUsz
      TjNUQjRLcW15TTd5eUYraVpYU09iWG44akhHN3FMMTQ5WnNsdkt0bmo5OE0KM3l1ZWNtNGd6c3Iv
      R3BGVjgwUG5ZY3pEaXRYSldJS2NPUzBNRVU4NWVOV3hWSnBpQjJmbWt5S2ZSRGh4T1N4YwpKWlhN
      ZmdhS20xYlZ6RkVva0JnL3FSYTJaZFZCdWJHTFdjRW5NMEpJM2J4OHFBRTUvY29nTkozK2FOcFNj
      ZlpDCndEcVB2blhuajNHdWh1VTRERFlOWDYrcjhCSzkxcFNvU3cwQXMyQlZFeDcwb1QvaFJuRnQz
      UXdjUDAxenNlRXcKZkhmZDI1aWQvQ1JEWUZ6M3J0R0hOV1E4dnZnTmN4R2tTZ21Nb1FETU9BV1pQ
      V2V1dFV3NzhVT0tOcmkzdEIxWQo5NmZuQmR5Y2I2NXJnY3ZLL05YcEZJWDNIMDlsMVZKODNXTTJS
      cnkwMzBzQTdEYzAzYzJRSXozOHBoZXpRMnA3Ckwxbzl1TW5TbUI5UFlQTGNoQkxRV1o1K05MMnBH
      STRqNnJhZ1lJM0VMSmdzQm5MdTNGeVhpOUhOTTY2eVd6UzAKM1lnczUzWVpvZzFHZ3dyS1pSUVlO
      VlBla2VmOGZsRHJXU1dUYklaejVaWT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K

jwt:
  key:
    passphrase: password
    publicKey: |-
      LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFE
      Q0JpUUtCZ1FETzlNQkNTYXVRWU5EY0hZc01GWXM5VlIzZQpSWThZbXFHRERNcjdteTRaeEUxV2x0
      c2lZUFJGNjBCM1NTMElsSUIvcWgvcnVoZ1FFRUN4OG53dVpvcnNxd0JoCkk2bU10UGpvQ2o5U2dx
      K2hRckoveDNnemFGOW5XN3hjTDVkbUhwdVdhOTZhaHY3RUdRbWtPcmZCL0JkYVo3MFcKZmZoTk9E
      QlRUNDZMM1haWU1RSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
    privateKey: |-
      LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRF
      Sy1JbmZvOiBBRVMtMTI4LUNCQyxFMjJCRUI4QUEwMjQ2MEY2ODAxN0MzOTQ5OUU4NTM4RAoKaUpH
      ZHFybUxMUHZUMTBLUG5aN1B3bHlrSGdBUExibFdPeFM5aFBrQ3VnVC83ejJNempwOTlzcDREOTRt
      NGFyNwpKMkljTlNLUm9hTEtsZDZ5am1acTFhNTBoWHZZV3YzamlVaVp3bnBKK1dYOE1Hbk94ODRS
      ZTJTM05GMXYxSlZrCjlFbE8venRmNmtDcG91N2xPTUJvS1hsUWhGa2ZMS29TRGZvVEdadytQdVZP
      UVcycmhweUNqeUpJUGVpZ0JaTE0KYnFINUYzdzFMd1RnUXA5cG1RdnNsWXFTNU1kS1lvWFc1dC92
      dTdxNGg1YzljTXFxZHpKRGlCajk0TWp1SEcvcgp0V2dRdC8yTnZSTDlySWQxcGNxWGRDeXVmV0ZW
      VDlCYzEzWlkwd3ZwT1FXdWVUTGdYYUx6Vi96LzVKNDlxVUNuCkFsSFozZHRHVnM4MkhkTzB2Unlo
      UnozNFdTczhaNDNpdktTalpueWJzeXJxeUVnYWpMcDVIQ3pzWnE3M09qN1cKaHg5QkZGZjBkTSt1
      SWhVNGtPeEhJREtaM3FEdllrcXN4ZHJ5SnMzTDFyNW5wSzF4N3g2bU9XaktXOVVvb041cAp2M3FT
      MlFzQWc5VkNKOTErRmlFREdNait5NzBhVmJrcGNOZ1RxN2lGZVA2aVk4cEt4aHp5bC9YYXFabUha
      OFZGCnpzck5QUW1iclkzQUM1QlhYbkVQN2VqTU1PTkZQa2h5TjNTSzJTY05YZWE0UVdoME9zN28z
      NGV2UTFOOUNDU3UKcWxTaENWcmVLSUhhM1JCS1hhUHQ1RFBvSUVkSS9VWlpMaVdQMWdSWWFneks0
      V3NQZmQvaVNvTkJVK1V5WG83QgpqNGhSSUkzTmYwUkZCc2pKZUVsRGdvbzc3VWwyRkd2L1pvaVU5
      SUw4VldpbUgwMnkzbVlqck9ZZG0wQzFMaFdHClN2ZDlOQ1h6azA4YUI4d0REN04wQzI0YVNxSitB
      eU5OOTJscUl3WHplRFJWamx4TkRqU3pEYlZ1UmNXWjRaUm4KWXhDQ3JLTUJ0eUw4Uy9tRlV6SVNs
      djh0Q3dEcURmWjdqOEVTVTA0Q3VlYmhnMCtSYjFqWXZ6MWUyV0NJNmFIWAotLS0tLUVORCBSU0Eg
      UFJJVkFURSBLRVktLS0tLQo=
